log:
	@mkdir -p ./logs ; rm -f ./logs/*.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./BusRide2-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/BusRide2-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./BusRide40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/BusRide40-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./ChessBoard2-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/ChessBoard2-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./ChessBoard40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/ChessBoard40-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./CoinToss4-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/CoinToss4-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./CoinToss40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/CoinToss40-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec_dur.lp ../axioms/fdec_dur-show.lp ./Commuter15-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/Commuter15-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./DeadOrAlive3-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/DeadOrAlive3-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./DeadOrAlive40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/DeadOrAlive40-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./Happy2-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/Happy2-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./Happy40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/Happy40-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./KitchenSink_M5-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/KitchenSink_M5-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./KitchenSink_M25-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/KitchenSink_M25-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./KitchenSink_M40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/KitchenSink_M40-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./RussianTurkey4-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/RussianTurkey4-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./RussianTurkey40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/RussianTurkey40-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./StolenCar2-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/StolenCar2-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./StolenCar40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/StolenCar40-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./StuffyRoom2-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/StuffyRoom2-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./StuffyRoom40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/StuffyRoom40-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./Supermarket12-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/Supermarket12-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./Supermarket40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/Supermarket40-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ../axioms/causal.lp ./ThielscherCircuit1-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/ThielscherCircuit1-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ../axioms/causal.lp ./ThielscherCircuit20-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/ThielscherCircuit20-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ../axioms/causal.lp ./ThielscherCircuit40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/ThielscherCircuit40-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./WalkingTurkey3-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/WalkingTurkey3-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./WalkingTurkey40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/WalkingTurkey40-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./Yale3-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/Yale3-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./Yale40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/Yale40-ea.log



	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./FallingObjectWithAntiTrajectory5-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/FallingObjectWithAntiTrajectory5-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./FallingObjectWithAntiTrajectory15-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/FallingObjectWithAntiTrajectory15-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./FallingObjectWithAntiTrajectory25-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/FallingObjectWithAntiTrajectory25-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./FallingObjectWithEvents5-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/FallingObjectWithEvents5-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./FallingObjectWithEvents20-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/FallingObjectWithEvents20-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./FallingObjectWithEvents25-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/FallingObjectWithEvents25-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./FallingObjectWithEvents40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/FallingObjectWithEvents40-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./HotAirBalloon3-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/HotAirBalloon3-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./HotAirBalloon15-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/HotAirBalloon15-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./HotAirBalloon20-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/HotAirBalloon20-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./HotAirBalloon40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/HotAirBalloon40-ea.log

	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./Telephone3-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/Telephone3-ea.log
	clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./Telephone40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh > logs/Telephone40-ea.log

