log:
	@mkdir -p ./logs ; rm -f ./logs/*.log ; exit 0

# clingo-lpx  --------------------------------------------------------------------------------------------------------------------------------------------------

	../../scripts/maketrace.sh "python ../fdec-incr.py ./BusRide2-ea.lp" logs/lpx-BusRide2-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./BusRide40-ea.lp" logs/lpx-BusRide40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py ./ChessBoard2-ea.lp" logs/lpx-ChessBoard2-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./ChessBoard40-ea.lp" logs/lpx-ChessBoard40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py ./CoinToss4-ea.lp" logs/lpx-CoinToss4-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./CoinToss40-ea.lp" logs/lpx-CoinToss40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --no_axioms ../axioms/fdec_dur.lp ../axioms/fdec_dur-show.lp ./Commuter15-ea.lp" logs/lpx-Commuter15-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py ./DeadOrAlive3-ea.lp" logs/lpx-DeadOrAlive3-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./DeadOrAlive40-ea.lp" logs/lpx-DeadOrAlive40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py ./Happy2-ea.lp" logs/lpx-Happy2-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./Happy40-ea.lp" logs/lpx-Happy40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py ./KitchenSink_M5-ea.lp" logs/lpx-KitchenSink_M5-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./KitchenSink_M25-ea.lp" logs/lpx-KitchenSink_M25-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./KitchenSink_M40-ea.lp" logs/lpx-KitchenSink_M40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py ./RussianTurkey4-ea.lp" logs/lpx-RussianTurkey4-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./RussianTurkey40-ea.lp" logs/lpx-RussianTurkey40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py ./StolenCar2-ea.lp" logs/lpx-StolenCar2-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./StolenCar40-ea.lp" logs/lpx-StolenCar40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py ./StuffyRoom2-ea.lp" logs/lpx-StuffyRoom2-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./StuffyRoom40-ea.lp" logs/lpx-StuffyRoom40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py ./Supermarket12-ea.lp" logs/lpx-Supermarket12-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./Supermarket40-ea.lp" logs/lpx-Supermarket40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py ../axioms/causal.lp ./ThielscherCircuit1-ea.lp" logs/lpx-ThielscherCircuit1-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ../axioms/causal.lp ./ThielscherCircuit20-ea.lp" logs/lpx-ThielscherCircuit20-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ../axioms/causal.lp ./ThielscherCircuit40-ea.lp" logs/lpx-ThielscherCircuit40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py ./WalkingTurkey3-ea.lp" logs/lpx-WalkingTurkey3-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./WalkingTurkey40-ea.lp" logs/lpx-WalkingTurkey40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py ./Yale3-ea.lp" logs/lpx-Yale3-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./Yale40-ea.lp" logs/lpx-Yale40-ea.log ; exit 0



	../../scripts/maketrace.sh "python ../fdec-incr.py ./FallingObjectWithAntiTrajectory5-ea.lp" logs/lpx-FallingObjectWithAntiTrajectory5-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./FallingObjectWithAntiTrajectory15-ea.lp" logs/lpx-FallingObjectWithAntiTrajectory15-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./FallingObjectWithAntiTrajectory25-ea.lp" logs/lpx-FallingObjectWithAntiTrajectory25-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py ./FallingObjectWithEvents5-ea.lp" logs/lpx-FallingObjectWithEvents5-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./FallingObjectWithEvents20-ea.lp" logs/lpx-FallingObjectWithEvents20-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./FallingObjectWithEvents25-ea.lp" logs/lpx-FallingObjectWithEvents25-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./FallingObjectWithEvents40-ea.lp" logs/lpx-FallingObjectWithEvents40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py ./HotAirBalloon3-ea.lp" logs/lpx-HotAirBalloon3-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./HotAirBalloon15-ea.lp" logs/lpx-HotAirBalloon15-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./HotAirBalloon20-ea.lp" logs/lpx-HotAirBalloon20-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./HotAirBalloon40-ea.lp" logs/lpx-HotAirBalloon40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py ./Telephone3-ea.lp" logs/lpx-Telephone3-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py ./Telephone40-ea.lp" logs/lpx-Telephone40-ea.log ; exit 0


# clingcon  --------------------------------------------------------------------------------------------------------------------------------------------------

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./BusRide2-ea.lp" logs/con-BusRide2-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./BusRide40-ea.lp" logs/con-BusRide40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./ChessBoard2-ea.lp" logs/con-ChessBoard2-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./ChessBoard40-ea.lp" logs/con-ChessBoard40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./CoinToss4-ea.lp" logs/con-CoinToss4-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./CoinToss40-ea.lp" logs/con-CoinToss40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con --no_axioms ../axioms/fdec_dur.lp ../axioms/fdec_dur-show.lp ./Commuter15-ea.lp" logs/con-Commuter15-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./DeadOrAlive3-ea.lp" logs/con-DeadOrAlive3-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./DeadOrAlive40-ea.lp" logs/con-DeadOrAlive40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./Happy2-ea.lp" logs/con-Happy2-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./Happy40-ea.lp" logs/con-Happy40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./KitchenSink_M5-ea.lp" logs/con-KitchenSink_M5-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./KitchenSink_M25-ea.lp" logs/con-KitchenSink_M25-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./KitchenSink_M40-ea.lp" logs/con-KitchenSink_M40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./RussianTurkey4-ea.lp" logs/con-RussianTurkey4-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./RussianTurkey40-ea.lp" logs/con-RussianTurkey40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./StolenCar2-ea.lp" logs/con-StolenCar2-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./StolenCar40-ea.lp  --project" logs/con-StolenCar40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./StuffyRoom2-ea.lp" logs/con-StuffyRoom2-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./StuffyRoom40-ea.lp" logs/con-StuffyRoom40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./Supermarket12-ea.lp" logs/con-Supermarket12-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./Supermarket40-ea.lp" logs/con-Supermarket40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ../axioms/causal.lp ./ThielscherCircuit1-ea.lp" logs/con-ThielscherCircuit1-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ../axioms/causal.lp ./ThielscherCircuit20-ea.lp" logs/con-ThielscherCircuit20-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ../axioms/causal.lp ./ThielscherCircuit40-ea.lp" logs/con-ThielscherCircuit40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./WalkingTurkey3-ea.lp" logs/con-WalkingTurkey3-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./WalkingTurkey40-ea.lp" logs/con-WalkingTurkey40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./Yale3-ea.lp" logs/con-Yale3-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./Yale40-ea.lp" logs/con-Yale40-ea.log ; exit 0



	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./FallingObjectWithAntiTrajectory5-ea.lp" logs/con-FallingObjectWithAntiTrajectory5-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./FallingObjectWithAntiTrajectory15-ea.lp" logs/con-FallingObjectWithAntiTrajectory15-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./FallingObjectWithAntiTrajectory25-ea.lp" logs/con-FallingObjectWithAntiTrajectory25-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./FallingObjectWithEvents5-ea.lp" logs/con-FallingObjectWithEvents5-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./FallingObjectWithEvents20-ea.lp" logs/con-FallingObjectWithEvents20-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./FallingObjectWithEvents25-ea.lp" logs/con-FallingObjectWithEvents25-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./FallingObjectWithEvents40-ea.lp" logs/con-FallingObjectWithEvents40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./HotAirBalloon3-ea.lp" logs/con-HotAirBalloon3-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./HotAirBalloon15-ea.lp" logs/con-HotAirBalloon15-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./HotAirBalloon20-ea.lp" logs/con-HotAirBalloon20-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./HotAirBalloon40-ea.lp" logs/con-HotAirBalloon40-ea.log ; exit 0

	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./Telephone3-ea.lp" logs/con-Telephone3-ea.log ; exit 0
	../../scripts/maketrace.sh "python ../fdec-incr.py --con ./Telephone40-ea.lp" logs/con-Telephone40-ea.log ; exit 0


compare:
	@echo BusRide2							&&  ../utils/compare-output.sh 		logs/lpx-BusRide2-ea.log							logs/con-BusRide2-ea.log 							> /dev/null && \
	echo BusRide40							&&  ../utils/compare-output.sh 		logs/lpx-BusRide40-ea.log							logs/con-BusRide40-ea.log 							> /dev/null && \
	echo ChessBoard2						&&  ../utils/compare-output.sh 		logs/lpx-ChessBoard2-ea.log							logs/con-ChessBoard2-ea.log 						> /dev/null && \
	echo ChessBoard40						&&  ../utils/compare-output.sh 		logs/lpx-ChessBoard40-ea.log						logs/con-ChessBoard40-ea.log 						> /dev/null && \
#	echo CoinToss4							&&  ../utils/compare-output.sh 		logs/lpx-CoinToss4-ea.log							logs/con-CoinToss4-ea.log 							> /dev/null && \
#	echo CoinToss40							&&  ../utils/compare-output.sh 		logs/lpx-CoinToss40-ea.log							logs/con-CoinToss40-ea.log 							> /dev/null && \
	echo Commuter15							&&  ../utils/compare-output.sh 		logs/lpx-Commuter15-ea.log							logs/con-Commuter15-ea.log 							> /dev/null && \
	echo DeadOrAlive3						&&  ../utils/compare-output.sh 		logs/lpx-DeadOrAlive3-ea.log						logs/con-DeadOrAlive3-ea.log 						> /dev/null && \
	echo DeadOrAlive40						&&  ../utils/compare-output.sh 		logs/lpx-DeadOrAlive40-ea.log						logs/con-DeadOrAlive40-ea.log 						> /dev/null && \
	echo Happy2								&&  ../utils/compare-output.sh 		logs/lpx-Happy2-ea.log								logs/con-Happy2-ea.log 								> /dev/null && \
	echo Happy40							&&  ../utils/compare-output.sh 		logs/lpx-Happy40-ea.log								logs/con-Happy40-ea.log 							> /dev/null && \
	echo KitchenSink_M5						&&  ../utils/compare-output.sh 		logs/lpx-KitchenSink_M5-ea.log						logs/con-KitchenSink_M5-ea.log 						> /dev/null && \
	echo KitchenSink_M25					&&  ../utils/compare-output.sh 		logs/lpx-KitchenSink_M25-ea.log						logs/con-KitchenSink_M25-ea.log 					> /dev/null && \
	echo KitchenSink_M40					&&  ../utils/compare-output.sh 		logs/lpx-KitchenSink_M40-ea.log						logs/con-KitchenSink_M40-ea.log 					> /dev/null && \
#	echo RussianTurkey4						&&  ../utils/compare-output.sh 		logs/lpx-RussianTurkey4-ea.log						logs/con-RussianTurkey4-ea.log 						> /dev/null && \
#	echo RussianTurkey40					&&  ../utils/compare-output.sh 		logs/lpx-RussianTurkey40-ea.log						logs/con-RussianTurkey40-ea.log 					> /dev/null && \
#	echo StolenCar2							&&  ../utils/compare-output.sh 		logs/lpx-StolenCar2-ea.log							logs/con-StolenCar2-ea.log 							> /dev/null && \
#	echo StolenCar40						&&  ../utils/compare-output.sh 		logs/lpx-StolenCar40-ea.log							logs/con-StolenCar40-ea.log 						> /dev/null && \
	echo StuffyRoom2						&&  ../utils/compare-output.sh 		logs/lpx-StuffyRoom2-ea.log							logs/con-StuffyRoom2-ea.log 						> /dev/null && \
	echo StuffyRoom40						&&  ../utils/compare-output.sh 		logs/lpx-StuffyRoom40-ea.log						logs/con-StuffyRoom40-ea.log 						> /dev/null && \
	echo Supermarket12						&&  ../utils/compare-output.sh 		logs/lpx-Supermarket12-ea.log						logs/con-Supermarket12-ea.log 						> /dev/null && \
	echo Supermarket40						&&  ../utils/compare-output.sh 		logs/lpx-Supermarket40-ea.log						logs/con-Supermarket40-ea.log 						> /dev/null && \
	echo ThielscherCircuit1					&&  ../utils/compare-output.sh 		logs/lpx-ThielscherCircuit1-ea.log					logs/con-ThielscherCircuit1-ea.log 					> /dev/null && \
	echo ThielscherCircuit20				&&  ../utils/compare-output.sh 		logs/lpx-ThielscherCircuit20-ea.log					logs/con-ThielscherCircuit20-ea.log 				> /dev/null && \
	echo ThielscherCircuit40				&&  ../utils/compare-output.sh 		logs/lpx-ThielscherCircuit40-ea.log					logs/con-ThielscherCircuit40-ea.log 				> /dev/null && \
	echo WalkingTurkey3						&&  ../utils/compare-output.sh 		logs/lpx-WalkingTurkey3-ea.log						logs/con-WalkingTurkey3-ea.log 						> /dev/null && \
	echo WalkingTurkey40					&&  ../utils/compare-output.sh 		logs/lpx-WalkingTurkey40-ea.log						logs/con-WalkingTurkey40-ea.log 					> /dev/null && \
	echo Yale3								&&  ../utils/compare-output.sh 		logs/lpx-Yale3-ea.log								logs/con-Yale3-ea.log 								> /dev/null && \
	echo Yale40								&&  ../utils/compare-output.sh 		logs/lpx-Yale40-ea.log								logs/con-Yale40-ea.log 								> /dev/null && \
	echo FallingObjectWithAntiTrajectory5	&&  ../utils/compare-output.sh 		logs/lpx-FallingObjectWithAntiTrajectory5-ea.log	logs/con-FallingObjectWithAntiTrajectory5-ea.log 	> /dev/null && \
	echo FallingObjectWithAntiTrajectory15	&&  ../utils/compare-output.sh 		logs/lpx-FallingObjectWithAntiTrajectory15-ea.log	logs/con-FallingObjectWithAntiTrajectory15-ea.log 	> /dev/null && \
	echo FallingObjectWithAntiTrajectory25	&&  ../utils/compare-output.sh 		logs/lpx-FallingObjectWithAntiTrajectory25-ea.log	logs/con-FallingObjectWithAntiTrajectory25-ea.log 	> /dev/null && \
	echo FallingObjectWithEvents5			&&  ../utils/compare-output.sh 		logs/lpx-FallingObjectWithEvents5-ea.log			logs/con-FallingObjectWithEvents5-ea.log 			> /dev/null && \
	echo FallingObjectWithEvents20			&&  ../utils/compare-output.sh 		logs/lpx-FallingObjectWithEvents20-ea.log			logs/con-FallingObjectWithEvents20-ea.log 			> /dev/null && \
	echo FallingObjectWithEvents25			&&  ../utils/compare-output.sh 		logs/lpx-FallingObjectWithEvents25-ea.log			logs/con-FallingObjectWithEvents25-ea.log 			> /dev/null && \
	echo FallingObjectWithEvents40			&&  ../utils/compare-output.sh 		logs/lpx-FallingObjectWithEvents40-ea.log			logs/con-FallingObjectWithEvents40-ea.log 			> /dev/null && \
	echo HotAirBalloon3						&&  ../utils/compare-output.sh 		logs/lpx-HotAirBalloon3-ea.log						logs/con-HotAirBalloon3-ea.log 						> /dev/null && \
	echo HotAirBalloon15					&&  ../utils/compare-output.sh 		logs/lpx-HotAirBalloon15-ea.log						logs/con-HotAirBalloon15-ea.log 					> /dev/null && \
	echo HotAirBalloon20					&&  ../utils/compare-output.sh 		logs/lpx-HotAirBalloon20-ea.log						logs/con-HotAirBalloon20-ea.log 					> /dev/null && \
	echo HotAirBalloon40					&&  ../utils/compare-output.sh 		logs/lpx-HotAirBalloon40-ea.log						logs/con-HotAirBalloon40-ea.log 					> /dev/null && \
	echo Telephone3							&&  ../utils/compare-output.sh 		logs/lpx-Telephone3-ea.log							logs/con-Telephone3-ea.log 							> /dev/null && \
	echo Telephone40						&&  ../utils/compare-output.sh 		logs/lpx-Telephone40-ea.log							logs/con-Telephone40-ea.log 						> /dev/null && \
	echo "\n  DONE (not checking random)\n"