clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./CoinToss4-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh
clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./CoinToss40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh

clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./DeadOrAlive3-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh
clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./DeadOrAlive40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh

clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./Happy2-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh
clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./Happy40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh

clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./KitchenSink_M5-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh
clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./KitchenSink_M25-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh
clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./KitchenSink_M40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh

clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./RussianTurkey4-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh
clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./RussianTurkey40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh

clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./StolenCar2-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh
clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./StolenCar40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh

clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./StuffyRoom2-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh
clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./StuffyRoom40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh

clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./Supermarket12-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh
clingo-lpx --strict -n0 ../axioms/fdec.lp ../axioms/fdec-show.lp ./Supermarket40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh

clingo-lpx --strict -n10 ../axioms/fdec.lp ../axioms/fdec-show.lp ./Yale3-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh
clingo-lpx --strict -n10 ../axioms/fdec.lp ../axioms/fdec-show.lp ./Yale40-ea.lp | ../utils/replace_assignments.sh | ../utils/make-readable.sh