log:
	@mkdir -p ./logs ; rm -f ./logs/*.log

	clingo -n10 ../axioms/dec_clingo.lp ./BusRide2-ea.lp > logs/BusRide2-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./BusRide40-ea.lp > logs/BusRide40-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo.lp ./ChessBoard2-ea.lp > logs/ChessBoard2-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./ChessBoard40-ea.lp > logs/ChessBoard40-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo.lp ./CoinToss4-ea.lp > logs/CoinToss4-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./CoinToss40-ea.lp > logs/CoinToss40-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo_dur.lp ./Commuter15-ea.lp > logs/Commuter15-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo.lp ./DeadOrAlive3-ea.lp > logs/DeadOrAlive3-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./DeadOrAlive40-ea.lp > logs/DeadOrAlive40-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo.lp ./Happy2-ea.lp > logs/Happy2-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./Happy40-ea.lp > logs/Happy40-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo.lp ./KitchenSink_M5-ea.lp > logs/KitchenSink_M5-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./KitchenSink_M25-ea.lp > logs/KitchenSink_M25-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./KitchenSink_M40-ea.lp > logs/KitchenSink_M40-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo.lp ./RussianTurkey4-ea.lp > logs/RussianTurkey4-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./RussianTurkey40-ea.lp > logs/RussianTurkey40-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo.lp ./StolenCar2-ea.lp > logs/StolenCar2-ea.log ; exit 0
	clingo -n1 ../axioms/dec_clingo.lp ./StolenCar40-ea.lp > logs/StolenCar40-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo.lp ./StuffyRoom2-ea.lp > logs/StuffyRoom2-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./StuffyRoom40-ea.lp > logs/StuffyRoom40-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo.lp ./Supermarket12-ea.lp > logs/Supermarket12-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./Supermarket40-ea.lp > logs/Supermarket40-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo.lp ../axioms/causal.lp ./ThielscherCircuit1-ea.lp > logs/ThielscherCircuit1-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ../axioms/causal.lp ./ThielscherCircuit20-ea.lp > logs/ThielscherCircuit20-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ../axioms/causal.lp ./ThielscherCircuit40-ea.lp > logs/ThielscherCircuit40-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo.lp ./WalkingTurkey3-ea.lp > logs/WalkingTurkey3-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./WalkingTurkey40-ea.lp > logs/WalkingTurkey40-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo.lp ./Yale3-ea.lp > logs/Yale3-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./Yale40-ea.lp > logs/Yale40-ea.log ; exit 0



	clingo -n10 ../axioms/dec_clingo.lp ./FallingObjectWithAntiTrajectory5-ea.lp > logs/FallingObjectWithAntiTrajectory5-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./FallingObjectWithAntiTrajectory15-ea.lp > logs/FallingObjectWithAntiTrajectory15-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./FallingObjectWithAntiTrajectory25-ea.lp > logs/FallingObjectWithAntiTrajectory25-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo.lp ./FallingObjectWithEvents5-ea.lp > logs/FallingObjectWithEvents5-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./FallingObjectWithEvents20-ea.lp > logs/FallingObjectWithEvents20-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./FallingObjectWithEvents25-ea.lp > logs/FallingObjectWithEvents25-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./FallingObjectWithEvents40-ea.lp > logs/FallingObjectWithEvents40-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo.lp ./HotAirBalloon3-ea.lp > logs/HotAirBalloon3-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./HotAirBalloon15-ea.lp > logs/HotAirBalloon15-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./HotAirBalloon20-ea.lp > logs/HotAirBalloon20-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./HotAirBalloon40-ea.lp > logs/HotAirBalloon40-ea.log ; exit 0

	clingo -n10 ../axioms/dec_clingo.lp ./Telephone3-ea.lp > logs/Telephone3-ea.log ; exit 0
	clingo -n10 ../axioms/dec_clingo.lp ./Telephone40-ea.lp > logs/Telephone40-ea.log ; exit 0

