measure-clingcon-domain:
	../scripts/test.sh ./clingcon-tasks.sh ../hybrid-clingo/ ../comparison/clingcon-domain-run/ 4 2 120
measure-clingolpx-domain:
	../scripts/test.sh ./clingolpx-tasks.sh ../hybrid-clingo/ ../comparison/clingolpx-domain-run/ 4 2 120
measure-clingo-domain:
	../scripts/test.sh ./clingo-tasks.sh ../clingo/ ../comparison/clingo-domain-run/ 4 2 120


measure-clingcon-events_and_precision:
	../scripts/test.sh ./clingcon-tasks-step_scaling.sh ../hybrid-clingo/ ../comparison/clingcon-event_precision-run/ 4 2 120
measure-clingolpx-events_and_precision:
	../scripts/test.sh ./clingolpx-tasks-step_scaling.sh ../hybrid-clingo/ ../comparison/clingolpx-event_precision-run/ 4 2 120
measure-clingo-events_and_precision:
	../scripts/test.sh ./clingo-tasks-step_scaling.sh ../clingo/ ../comparison/clingo-event_precision-run/ 4 2 120