measure-clingcon:
	../scripts/test.sh ./clingcon-tasks.sh ../hybrid-clingo/ ../comparison/clingcon-test-run/ 4 2 120
measure-clingolpx:
	../scripts/test.sh ./clingolpx-tasks.sh ../hybrid-clingo/ ../comparison/clingcon-test-run/ 4 2 120
measure-clingo:
	../scripts/test.sh ./clingo-tasks.sh ../clingo/ ../comparison/clingcon-test-run/ 4 2 120